#define IDD_MAIN                            101
#define IDC_STATIC                           -1
#define IDC_FILENAME                       1000
#define IDC_MESHNAME                       1001
#define IDC_RSTNAME                        1002
#define IDC_OUTNAME                        1003
#define IDC_LSTNAME                        1004
#define IDC_OPEN                           1005
#define IDC_RUN                            1006
#define IDC_CANCEL                         1007
#define IDC_PATH                           1008
#define IDC_STATUS                         1009
#define IDC_VFILE                          1010
#define IDC_VMESH                          1011
#define IDC_VLST                           1012
#define IDC_EDIT                           1013
#define IDC_CONSTNAME                          1014
#define IDC_VCONST                         1015
#define IDC_NLNAME                             1016
#define IDC_VNL                            1017
#define IDC_EXT                            1020
#define IDC_ZICON 99
